sudo: false
language: node_js

node_js:
  - stable

install:
  - npm install

before_script:
  - npm run deps

after_script:
  - cat coverage/report-lcov/lcov.info | node_modules/.bin/coveralls

script:
  - npm test
